### ISSUE TITLE
Fix full size Instagram profile image

### ISSUE THREAD

**Issue by Ondkloss** [Ondkloss/ig-vsco-fullsize#1]
Opening Instagram profile image now usually opens 320x320. There exists a larger edition found using the following method ([source](https://stackoverflow.com/questions/48468144/how-to-view-instagram-profile-picture-in-full-size)):

> Get the user_Id from `https://www.instagram.com/{username}/?__a=1` and get the profile pic url from `https://i.instagram.com/api/v1/users/{user_id}/info`

However it seems to require a cookie or some access token not easily available to the extension. The goal of this issue would be to be able to use this full size profile image, either through the mentioned method or some other avenue.

**Comment by dougfabris** [comment]
@Ondkloss Interesting project! I believe that I can help with this issue, can I work in that?

**Comment by Ondkloss** [comment]
Sure @dougfabris! Go ahead and give it a try!

**Comment by Ondkloss** [comment]
Fixed by applying the method in the issue text, as well as intercepting the request using the `webRequest` API and changing the user agent to allow access. This HD profile picture (max 1080x1080) relies on being logged in. If you are not it will still fall back to the version that is probably 320x320.
