### ISSUE TITLE
Add "Reels" of Instagram into the download possibilities

### ISSUE THREAD

**Issue by JohnPlanetary** [Ondkloss/ig-vsco-fullsize#7]
Thanks for the great IG_VSCO-FULLSIZE extension!

Since Instagram added REELS VIDEOS it would be nice for the extension to also support it =) and allow the user to download the content.
Usually something like: https://www.instagram.com/reel/{random_things}/

Thanks again for the great work!

**Comment by Ondkloss** [comment]
Thanks for reporting the issue @JohnPlanetary! I've submitted a new version to Chrome/Firefox which hopefully resolves this. It might take a couple of hours to be approved by each browser.
